config/routes.rb
Rails.application.routes.draw do
  resource :session
  resource :registration, only: %i[new create]
  resources :passwords, param: :token

  root "home#index"
  get "about", to: "home#about"

  get "edit_budget", to: "users#edit_budget"
  patch "update_budget", to: "users#update_budget"

  resources :subscriptions

  # chart paths
  get "charts/budget_v_actual", to: "charts#budget_v_actual"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user

  VALID_BILLING_FREQUENCIES = %w[monthly annual].freeze
  SUBSCRIPTION_NAMES = %w[
    netflix amazon_prime_video disney_plus hbo_max hulu apple_tv_plus peacock paramount_plus discovery_plus youtube_premium cruncyroll starz showtime britbox acorn_tv amc_plus mubi sling_tv fubo_tv philo
  ].freeze

  DOMAIN_MAPPING = {
    "netflix" => "netflix.com",
    "amazon_prime_video" => "primevideo.com",
    "disney_plus" => "disneyplus.com",
    "hbo_max" => "max.com",
    "hulu" => "hulu.com",
    "apple_tv_plus" => "tv.apple.com",
    "peacock" => "peacocktv.com",
    "paramount_plus" => "paramountplus.com",
    "discovery_plus" => "discoveryplus.com",
    "youtube_premium" => "youtube.com",
    "cruncyroll" => "crunchyroll.com",
    "starz" => "starz.com",
    "showtime" => "showtime.com",
    "britbox" => "britbox.com",
    "acorn_tv" => "acorn.tv",
    "amc_plus" => "amcplus.com",
    "mubi" => "mubi.com",
    "sling_tv" => "sling.com",
    "fubo_tv" => "fubo.tv",
    "philo" => "philo.com"
  }.freeze

  validates :name, presence: true, inclusion: { in: SUBSCRIPTION_NAMES }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validate :billing_frequency_case_insensitive_inclusion

  validate :started_at_not_nil
  validate :expires_at_not_nil
  validate :started_at_before_expires_at

  def active?
    return true if expires_at.nil?
    Time.current <= expires_at
  end

  def active_for_month?(month)
    return false if started_at.nil? || expires_at.nil?

    started_at <= month.end_of_month && expires_at >= month.beginning_of_month
  end

  def self.subscription_names
    SUBSCRIPTION_NAMES
  end

  def self.domain_for(name)
    DOMAIN_MAPPING[name]
  end

  private

  def billing_frequency_case_insensitive_inclusion
    unless VALID_BILLING_FREQUENCIES.include?(billing_frequency.to_s.downcase)
      errors.add(:billing_frequency, :inclusion, message: "is not included in the list")
    end
  end

  def started_at_not_nil
    errors.add(:started_at, "cannot be nil") if started_at.nil?
  end

  def expires_at_not_nil
    errors.add(:expires_at, "cannot be nil") if expires_at.nil?
  end

  def started_at_before_expires_at
    return if started_at.nil? || expires_at.nil?
    errors.add(:expires_at, "must be after the start date") if started_at > expires_at
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def index
    if params[:search].present?
      @subscriptions = Current.user.subscriptions.where("name ILIKE ?", "%#{params[:search]}%")
    else
      @subscriptions = Current.user.subscriptions
    end

    respond_to do |format|
      format.html
      format.js { render partial: "subscriptions_list", locals: { subscriptions: @subscriptions } }
    end
  end

  def show
    @subscription = Current.user.subscriptions.find(params[:id])
  end

  def new
    @subscription = Current.user.subscriptions.new
  end

  def create
    @subscription = Current.user.subscriptions.new(subscription_params)
    if @subscription.save
      redirect_to @subscription, notice: "Subscription was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @subscription = Current.user.subscriptions.find(params[:id])
  end

  def update
    @subscription = Current.user.subscriptions.find(params[:id])
    if @subscription.update(subscription_params)
      redirect_to @subscription, notice: "Subscription was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @subscription = Current.user.subscriptions.find(params[:id])
    @subscription.destroy
    redirect_to subscriptions_path, notice: "Subscription was successfully destroyed."
  end

  private

  def subscription_params
    params.require(:subscription).permit(:name, :price, :billing_frequency, :started_at, :expires_at)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  include ActualCost

  def currency_symbol(locale)
    I18n.t("number.currency.#{locale}.symbol", default: I18n.t("number.currency.default.symbol"))
  end

  def render_subscription_summary_table(subscriptions:, budget:, locale:)
    budget_set = budget.present?
    monthly_actual = total_cost(subscriptions, "monthly")
    annual_actual = total_cost(subscriptions, "annual")
    monthly_budget = budget_set ? sprintf("%.2f", (budget / 12).round(2)) : "Budget not set"
    annual_budget = budget_set ? sprintf("%.2f", budget.round(2)) : "Budget not set"
    currency_symbol = currency_symbol(locale)

    render partial: "subscriptions/summary/table", locals: {
      subscriptions: subscriptions,
      budget_set: budget_set,
      monthly_actual: monthly_actual,
      annual_actual: annual_actual,
      monthly_budget: monthly_budget,
      annual_budget: annual_budget,
      currency_symbol: currency_symbol
    }
  end

  def formatted_subscription_name(name)
    name.titleize
  end

  def formatted_subscription_names
    Subscription.subscription_names.map { |name| [ formatted_subscription_name(name), name ] }
  end
end

app/views/subscriptions/summary/_index.html.erb
<%= column_chart charts_budget_v_actual_path(
  annual_budget: Current.user.budget,
  frequency: "monthly",
) %>

<div class="relative w-full overflow-auto" data-controller="subscription">
  <%= render_collapsible do %>
    <% collapsible_preview do %>
      <h2 class="text-2xl font-semibold mb-4">Summary</h2>
    <% end %>
    <% collapsible_body do %>
      <%= render_subscription_summary_table(
        subscriptions: subscriptions,
        budget: Current.user.budget,
        locale: Current.user.locale
      ) %>
    <% end %>
    <% collapsed_element do %>
      <%= render partial: 'subscriptions/summary/table_skeleton' %>
    <% end %>
  <% end %>
</div>

app/views/subscriptions/summary/_table.html.erb
<table class="w-full caption-bottom border-border border-2 text-sm">
  <thead class="[&_tr]:border-b">
    <tr class="border-b border-border text-text transition-colors bg-main font-base data-[state=selected]:bg-white data-[state=selected]:text-text">
      <th class="h-12 px-4 text-left align-middle font-heading text-text [&:has([role=checkbox])]:pr-0 w-[100px]">
        Type
      </th>
      <th class="h-12 px-4 text-left align-middle font-heading text-text [&:has([role=checkbox])]:pr-0 w-[100px]">
        Actual
      </th>
      <th class="h-12 px-4 text-left align-middle font-heading text-text [&:has([role=checkbox])]:pr-0 w-[100px]">
        Budget
      </th>
      <th class="h-12 px-4 text-left align-middle font-heading text-text [&:has([role=checkbox])]:pr-0 w-[100px]">
        Actions
      </th>
    </tr>
  </thead>
  <tbody class="[&_tr:last-child]:border-0">
    <tr class="border-b border-border text-text transition-colors bg-main font-base data-[state=selected]:bg-white data-[state=selected]:text-text">
      <td class="p-4 align-middle [&:has([role=checkbox])]:pr-0 font-base">
        Monthly
      </td>
      <td class="p-4 align-middle [&:has([role=checkbox])]:pr-0 font-base">
        <%= currency_symbol %>
        <span data-subscription-target="monthlyActualValue">
          <%= monthly_actual %>
        </span>
      </td>
      <td class="p-4 align-middle [&:has([role=checkbox])]:pr-0 font-base">
        <span data-subscription-target="monthlyBudgetCurrencySymbol">
          <%=
              currency_symbol if budget_set
            %>
        </span>
        <span id="monthly-budget-display" data-subscription-target="monthlyBudgetDisplay" class="w-full <%= 'text-red-600' unless budget_set %>">
          <%= monthly_budget %>
        </span>
        <%= render_input(
              name: 'monthly_budget',
              value: monthly_budget,
              data: {
                controller: 'subscription',
                target: 'monthlyBudgetInput',
                action: 'keydown->subscription#handleKeydown'
              },
              id: 'monthly-budget-input',
              class: 'hidden',
              width: '[100px]'
          ) %>
      </td>
      <td class="p-4 align-middle [&:has([role=checkbox])]:pr-0 font-base flex items-center justify-start space-x-2">
        <%= render_button(
              text: 'Edit',
              icon: 'fa-regular fa-pen-to-square',
              link: '#',
              button_type: 'link_to',
              data: {
                controller: 'subscription',
                action: 'click->subscription#toggleMonthlyBudgetEdit',
                target: 'editMonthlyButton'
              },
              bg_class: 'bg-blue-500 text-white',
              id: 'edit-monthly-budget',
            ) %>
        <%= render_button(
              text: 'Save',
              icon: 'fa-regular fa-floppy-disk',
              link: '#',
              button_type: 'link_to',
              data: {
                controller: 'subscription',
                action: 'click->subscription#saveMonthlyBudget',
                target: 'saveMonthlyButton'
              },
              bg_class: 'bg-green-500 text-white',
              class: 'hidden',
              id: 'save-monthly-budget'
            ) %>
        <%= render_button(
              text: 'Cancel',
              icon: 'fa-solid fa-xmark',
              link: '#',
              button_type: 'link_to',
              data: {
                controller: 'subscription',
                action: 'click->subscription#toggleMonthlyBudgetEdit',
                target: 'cancelMonthlyButton'
              },
              bg_class: 'bg-gray-500 text-white',
              class: 'hidden',
              id: 'cancel-monthly-budget'
            ) %>
      </td>
    </tr>
    <tr class="border-b border-border text-text transition-colors bg-main font-base data-[state=selected]:bg-white data-[state=selected]:text-text">
      <td class="p-4 align-middle [&:has([role=checkbox])]:pr-0 font-base">
        Annual (next 12 months)
      </td>
      <td class="p-4 align-middle [&:has([role=checkbox])]:pr-0 font-base">
        <%= currency_symbol %>
        <span>
          <%= annual_actual %>
        </span>
      </td>
      <td class="p-4 align-middle [&:has([role=checkbox])]:pr-0 font-base">
        <span data-subscription-target="annualBudgetCurrencySymbol">
          <%=
              currency_symbol if budget_set
            %>
        </span>
        <span id="annual-budget-display" data-subscription-target="annualBudgetDisplay" class="w-full <%= 'text-red-600' unless budget_set %>">
          <%= annual_budget %>
        </span>
        <%= render_input(
              name: 'annual_budget',
              value: annual_budget,
              data: {
                controller: 'subscription',
                target: 'annualBudgetInput',
                action: 'keydown->subscription#handleKeydown'
              },
              id: 'annual-budget-input',
              class: 'hidden',
              width: '[100px]'
          ) %>
      </td>
      <td class="p-4 align-middle [&:has([role=checkbox])]:pr-0 font-base flex items-center justify-start space-x-2">
        <%= render_button(
              text: 'Edit',
              icon: 'fa-regular fa-pen-to-square',
              link: '#',
              button_type: 'link_to',
              data: {
                controller: 'subscription',
                action: 'click->subscription#toggleAnnualBudgetEdit',
                target: 'editAnnualButton'
              },
              bg_class: 'bg-blue-500 text-white',
              id: 'edit-annual-budget',
            ) %>
        <%= render_button(
              text: 'Save',
              icon: 'fa-regular fa-floppy-disk',
              link: '#',
              button_type: 'link_to',
              data: {
                controller: 'subscription',
                action: 'click->subscription#saveAnnualBudgetEdit',
                target: 'saveAnnualButton'
              },
              bg_class: 'bg-green-500 text-white0',
              id: 'save-annual-budget',
              class: 'hidden'
            ) %>
        <%= render_button(
              text: 'Cancel',
              icon: 'fa-solid fa-xmark',
              link: '#',
              button_type: 'link_to',
              data: {
                controller: 'subscription',
                action: 'click->subscription#toggleAnnualBudgetEdit',
                target: 'cancelAnnualButton'
              },
              bg_class: 'bg-gray-500 text-white',
              id: 'cancel-annual-budget',
              class: 'hidden'
            ) %>
      </td>
    </tr>
  </tbody>
  <caption data-subscription-target="summaryText" class="mt-4 m1000:min-h-20 w-full text-white text-center p-8 rounded-base border-2 border-border"></caption>
</table>

app/views/subscriptions/summary/_table_skeleton.html.erb
<table class="w-full caption-bottom border-border border-2 text-sm">
  <thead class="[&_tr]:border-b">
    <tr class="border-b border-border text-text transition-colors bg-main font-base data-[state=selected]:bg-white data-[state=selected]:text-text">
      <th class="h-12 px-4 text-left align-middle font-heading text-text [&:has([role=checkbox])]:pr-0 w-[100px]">
        Type
      </th>
      <th class="h-12 px-4 text-left align-middle font-heading text-text [&:has([role=checkbox])]:pr-0 w-[100px]">
        Actual
      </th>
      <th class="h-12 px-4 text-left align-middle font-heading text-text [&:has([role=checkbox])]:pr-0 w-[100px]">
        Budget
      </th>
      <th class="h-12 px-4 text-left align-middle font-heading text-text [&:has([role=checkbox])]:pr-0 w-[100px]">
        Actions
      </th>
    </tr>
  </thead>
</table>