config/routes.rb
Rails.application.routes.draw do
  resource :session
  resource :registration, only: %i[new create]
  resources :passwords, param: :token

  root "home#index"
  get "about", to: "home#about"

  get "edit_budget", to: "users#edit_budget"
  patch "update_budget", to: "users#update_budget"

  resources :subscriptions

  # chart paths
  get "charts/budget_v_actual", to: "charts#budget_v_actual"
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, message| %>
  <div data-controller="flash" class="<%= flash_class(key) %>" role="alert">
    <span class="block sm:inline"><%= message %></span>
    <button type="button" data-action="click->flash#close" class="ml-4">
      <i class="fa-solid fa-xmark"></i>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="fixed left-0 top-0 z-20 mx-auto flex h-[88px] w-full items-center border-b-4 border-border bg-white px-5 m500:h-16">
  <div class="container mx-auto flex justify-between items-center">
    <div class="flex items-center space-x-4">
      <%= link_to "Home", root_path, class: "text-xl m1100:text-base font-base" %>
      <%= link_to "Subscriptions", subscriptions_path, class: "text-xl m1100:text-base font-base" %>
      <%= link_to "About", about_path, class: "text-xl m1100:text-base font-base" %>
    </div>
    <div class="flex items-center space-x-4">
      <% if authenticated? %>
        <%= render_button(
          text: 'Log out',
          link: session_path,
          button_type: 'button_to',
          method: :delete,
          bg_class: 'bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600',
        ) %>
      <% else %>
        <%= render_button(
          text: 'Log in',
          link: new_session_path,
          button_type: 'button_to',
          method: :get
        ) %>
      <% end %>
    </div>
  </div>
</nav>